#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ! -d "vendor" ]; then
    export COMPOSER_PROCESS_TIMEOUT=2000
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        composer install
    else
        gosu $WWWUSER composer install
    fi
fi

if [ ! -f "public/build/manifest.json" ]; then
    echo "Vite manifest not found. Building frontend assets..."
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        npm install && npm run build
    else
        gosu $WWWUSER bash -c "npm install && npm run build"
    fi
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    # Run migrations and seed
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        php artisan migrate --force --seed
    else
        gosu $WWWUSER php artisan migrate --force --seed
    fi

    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
